### ISSUE TITLE
Add ability to directly assume credentials or generate a console link in a sub-account

### ISSUE THREAD

**Issue by iamkirkbater** [app-sre/rh-aws-saml-login#37]
The previous workflow we had was that we had credentials for all of the payer accounts saved on our laptops, and then it was a one step procedure to generate credentials or a console login link via `osdctl account console -i [account-number] -p [payer-account-name]`.

With this new flow through rh-aws-saml-login it would be nice to be able to pass an additional argument that would allow me to drop right into a sub account, through the specified payer account, instead of having to drop into the shell that's created as part of rh-aws-saml-login and run a further step to get into the account that I am looking for.

Non-Goal - I would not expect these sub-accounts to be listed by the rh-aws-saml-login tool, there are just too many (and the ability to query them is heavily rate limited by AWS) and it would not be a good user experience. We should expect the end users who use this functionality to know the account ID that they're trying to access.

**Comment by iamkirkbater** [comment]
Thanks for looking! No rush! This is 100% a convenience feature request :)

**Comment by chassing** [comment]
The version [0.7.0](https://pypi.org/project/rh-aws-saml-login/) has been released. It now supports `--assume-uid` to assume a role in a different account. See the [documenation](https://github.com/app-sre/rh-aws-saml-login#assume-role) for more details.
